# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure Functions

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '18.x'
  RESOURCE_GROUP: 'hai-server_group'
  FUNCTION_APP_NAME: 'hai-server'
  REGION: 'eastus'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set Azure Subscription'
      run: |
        az account set --subscription ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        az account show

    - name: 'Verify Function App'
      run: |
        echo "Checking Function App existence..."
        az functionapp show --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}

    - name: Install Azure Functions Core Tools
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

    - name: 'Clean Install Dependencies'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        rm -rf node_modules package-lock.json
        npm install --production
        npm run build --if-present
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true
        scm-do-build-during-deployment: true

    - name: 'Configure Azure Function App Settings'
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        app-settings-json: |
          [
            {
              "name": "OPENAI_API_KEY",
              "value": "${{ secrets.OPENAI_API_KEY }}"
            },
            {
              "name": "ASSISTANT_ID",
              "value": "${{ secrets.ASSISTANT_ID }}"
            },
            {
              "name": "FUNCTIONS_WORKER_RUNTIME",
              "value": "node"
            },
            {
              "name": "WEBSITE_NODE_DEFAULT_VERSION",
              "value": "~18"
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            }
          ]

    - name: 'Configure CORS'
      run: |
        az functionapp cors add --name ${{ env.FUNCTION_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --allowed-origins "http://localhost:3000" "https://haiconsultingservices.com" "https://www.haiconsultingservices.com" \
          --allowed-methods "GET" "POST" "OPTIONS" \
          --allowed-headers "Content-Type" "Authorization" \
          --exposed-headers "*"
